*NCAA School Name to ID Conversion

gen scode=.

rename school sname

replace scode= 501 if sname=="Abilene Chr"
replace scode= 501 if sname=="Abilene Christian Wildcats"
replace scode= 502 if sname=="Air Force"
replace scode= 502 if sname=="Air Force Falcons"
replace scode= 503 if sname=="Akron"
replace scode= 503 if sname=="Akron Zips"
replace scode= 504 if sname=="Alabama"
replace scode= 504 if sname=="Alabama Crimson Tide"
replace scode= 505 if sname=="Alabama A&M"
replace scode= 505 if sname=="Alabama A&M Bulldogs"
replace scode= 506 if sname=="Alabama St"
replace scode= 506 if sname=="Alabama State Hornets"
replace scode= 507 if sname=="Albany NY"
replace scode= 507 if sname=="Albany (NY) Great Danes"
replace scode= 508 if sname=="Alcorn St"
replace scode= 508 if sname=="Alcorn State Braves"
replace scode= 509 if sname=="American Univ"
replace scode= 509 if sname=="American Eagles"
replace scode= 510 if sname=="Appalachian St"
replace scode= 510 if sname=="Appalachian State Mountaineers"
replace scode= 511 if sname=="Arizona"
replace scode= 511 if sname=="Arizona Wildcats"
replace scode= 512 if sname=="Arizona St"
replace scode= 512 if sname=="Arizona State Sun Devils"
replace scode= 513 if sname=="Ark Little Rock"
replace scode= 513 if sname=="Arkansas-Little Rock Trojans"
replace scode= 514 if sname=="Ark Pine Bluff"
replace scode= 514 if sname=="Arkansas-Pine Bluff Golden Lions"
replace scode= 515 if sname=="Arkansas"
replace scode= 515 if sname=="Arkansas Razorbacks"
replace scode= 516 if sname=="Arkansas St"
replace scode= 516 if sname=="Arkansas State Red Wolves"
replace scode= 517 if sname=="Army"
replace scode= 517 if sname=="Army Black Knights"
replace scode= 518 if sname=="Auburn"
replace scode= 518 if sname=="Auburn Tigers"
replace scode= 519 if sname=="Austin Peay"
replace scode= 519 if sname=="Austin Peay Governors"
replace scode= 520 if sname=="Ball St"
replace scode= 520 if sname=="Ball State Cardinals"
replace scode= 521 if sname=="Baylor"
replace scode= 521 if sname=="Baylor Bears"
replace scode= 522 if sname=="Belmont"
replace scode= 522 if sname=="Belmont Bruins"
replace scode= 523 if sname=="Bethune-Cookman"
replace scode= 523 if sname=="Bethune-Cookman Wildcats"
replace scode= 524 if sname=="Binghamton"
replace scode= 524 if sname=="Binghamton Bearcats"
replace scode= 525 if sname=="Birmingham So"
replace scode= 525 if sname=="Birmingham-Southern Panthers"
replace scode= 526 if sname=="Boise St"
replace scode= 526 if sname=="Boise State Broncos"
replace scode= 527 if sname=="Boston College"
replace scode= 527 if sname=="Boston College Eagles"
replace scode= 528 if sname=="Boston Univ"
replace scode= 528 if sname=="Boston University Terriers"
replace scode= 529 if sname=="Bowling Green"
replace scode= 529 if sname=="Bowling Green State Falcons"
replace scode= 530 if sname=="Bradley"
replace scode= 530 if sname=="Bradley Braves"
replace scode= 531 if sname=="Brown"
replace scode= 531 if sname=="Brown Bears"
replace scode= 532 if sname=="Bryant"
replace scode= 532 if sname=="Bryant Bulldogs"
replace scode= 533 if sname=="Bucknell"
replace scode= 533 if sname=="Bucknell Bison"
replace scode= 534 if sname=="Buffalo"
replace scode= 534 if sname=="Buffalo Bulls"
replace scode= 535 if sname=="Butler"
replace scode= 535 if sname=="Butler Bulldogs"
replace scode= 536 if sname=="BYU"
replace scode= 536 if sname=="Brigham Young Cougars"
replace scode= 537 if sname=="C Michigan"
replace scode= 537 if sname=="Central Michigan Chippewas"
replace scode= 538 if sname=="Cal Poly SLO"
replace scode= 538 if sname=="Cal Poly SLO"
replace scode= 539 if sname=="California"
replace scode= 539 if sname=="California Golden Bears"
replace scode= 540 if sname=="Campbell"
replace scode= 540 if sname=="Campbell Fighting Camels"
replace scode= 541 if sname=="Canisius"
replace scode= 541 if sname=="Canisius Golden Griffins"
replace scode= 542 if sname=="Cent Arkansas"
replace scode= 542 if sname=="Central Arkansas Bears"
replace scode= 543 if sname=="Centenary"
replace scode= 543 if sname=="Centenary (LA) Gents"
replace scode= 544 if sname=="Central Conn"
replace scode= 544 if sname=="Central Connecticut State Blue Devils"
replace scode= 545 if sname=="Charleston So"
replace scode= 545 if sname=="Charleston Southern Buccaneers"
replace scode= 546 if sname=="Charlotte"
replace scode= 546 if sname=="Charlotte 49ers"
replace scode= 547 if sname=="Chattanooga"
replace scode= 547 if sname=="Chattanooga Mocs"
replace scode= 548 if sname=="Chicago St"
replace scode= 548 if sname=="Chicago State Cougars"
replace scode= 549 if sname=="Cincinnati"
replace scode= 549 if sname=="Cincinnati Bearcats"
replace scode= 550 if sname=="Citadel"
replace scode= 550 if sname=="Citadel Bulldogs"
replace scode= 551 if sname=="Clemson"
replace scode= 551 if sname=="Clemson Tigers"
replace scode= 552 if sname=="Cleveland St"
replace scode= 552 if sname=="Cleveland State Vikings"
replace scode= 553 if sname=="Coastal Car"
replace scode= 553 if sname=="Coastal Carolina Chanticleers"
replace scode= 554 if sname=="Col Charleston"
replace scode= 554 if sname=="College of Charleston Cougars"
replace scode= 555 if sname=="Colgate"
replace scode= 555 if sname=="Colgate Raiders"
replace scode= 556 if sname=="Colorado"
replace scode= 556 if sname=="Colorado Buffaloes"
replace scode= 557 if sname=="Colorado St"
replace scode= 557 if sname=="Colorado State Rams"
replace scode= 558 if sname=="Columbia"
replace scode= 558 if sname=="Columbia Lions"
replace scode= 559 if sname=="Connecticut"
replace scode= 559 if sname=="Connecticut Huskies"
replace scode= 560 if sname=="Coppin St"
replace scode= 560 if sname=="Coppin State Eagles"
replace scode= 561 if sname=="Cornell"
replace scode= 561 if sname=="Cornell Big Red"
replace scode= 562 if sname=="Creighton"
replace scode= 562 if sname=="Creighton Bluejays"
replace scode= 563 if sname=="CS Bakersfield"
replace scode= 563 if sname=="Cal State Bakersfield Roadrunners"
replace scode= 564 if sname=="CS Fullerton"
replace scode= 564 if sname=="Cal State Fullerton Titans"
replace scode= 565 if sname=="CS Northridge"
replace scode= 565 if sname=="Cal State Northridge Matadors"
replace scode= 566 if sname=="CS Sacramento"
replace scode= 566 if sname=="Sacramento State Hornets"
replace scode= 567 if sname=="Dartmouth"
replace scode= 567 if sname=="Dartmouth Big Green"
replace scode= 568 if sname=="Davidson"
replace scode= 568 if sname=="Davidson Wildcats"
replace scode= 569 if sname=="Dayton"
replace scode= 569 if sname=="Dayton Flyers"
replace scode= 570 if sname=="Delaware"
replace scode= 570 if sname=="Delaware Fightin' Blue Hens"
replace scode= 571 if sname=="Delaware St"
replace scode= 571 if sname=="Delaware State Hornets"
replace scode= 572 if sname=="Denver"
replace scode= 572 if sname=="Denver Pioneers"
replace scode= 573 if sname=="DePaul"
replace scode= 573 if sname=="DePaul Blue Demons"
replace scode= 574 if sname=="Detroit"
replace scode= 574 if sname=="Detroit Mercy Titans"
replace scode= 575 if sname=="Drake"
replace scode= 575 if sname=="Drake Bulldogs"
replace scode= 576 if sname=="Drexel"
replace scode= 576 if sname=="Drexel Dragons"
replace scode= 577 if sname=="Duke"
replace scode= 577 if sname=="Duke Blue Devils"
replace scode= 578 if sname=="Duquesne"
replace scode= 578 if sname=="Duquesne Dukes"
replace scode= 579 if sname=="E Illinois"
replace scode= 579 if sname=="Eastern Illinois Panthers"
replace scode= 580 if sname=="E Kentucky"
replace scode= 580 if sname=="Eastern Kentucky Colonels"
replace scode= 581 if sname=="E Michigan"
replace scode= 581 if sname=="Eastern Michigan Eagles"
replace scode= 582 if sname=="E Washington"
replace scode= 582 if sname=="Eastern Washington Eagles"
replace scode= 583 if sname=="East Carolina"
replace scode= 583 if sname=="East Carolina Pirates"
replace scode= 584 if sname=="Edwardsville"
replace scode= 584 if sname=="Southern Illinois-Edwardsville Cougars"
replace scode= 585 if sname=="Elon"
replace scode= 585 if sname=="Elon Phoenix"
replace scode= 586 if sname=="ETSU"
replace scode= 586 if sname=="East Tennessee State Buccaneers"
replace scode= 587 if sname=="Evansville"
replace scode= 587 if sname=="Evansville Purple Aces"
replace scode= 588 if sname=="F Dickinson"
replace scode= 588 if sname=="Fairleigh Dickinson Knights"
replace scode= 589 if sname=="Fairfield"
replace scode= 589 if sname=="Fairfield Stags"
replace scode= 590 if sname=="FL Atlantic"
replace scode= 590 if sname=="Florida Atlantic Owls"
replace scode= 591 if sname=="FL Gulf Coast"
replace scode= 591 if sname=="Florida Gulf Coast Eagles"
replace scode= 592 if sname=="Florida"
replace scode= 592 if sname=="Florida Gators"
replace scode= 593 if sname=="Florida A&M"
replace scode= 593 if sname=="Florida A&M Rattlers"
replace scode= 594 if sname=="Florida Intl"
replace scode= 594 if sname=="Florida International Panthers"
replace scode= 595 if sname=="Florida St"
replace scode= 595 if sname=="Florida State Seminoles"
replace scode= 596 if sname=="Fordham"
replace scode= 596 if sname=="Fordham Rams"
replace scode= 597 if sname=="Fresno St"
replace scode= 597 if sname=="Fresno State Bulldogs"
replace scode= 598 if sname=="Furman"
replace scode= 598 if sname=="Furman Paladins"
replace scode= 599 if sname=="G Washington"
replace scode= 599 if sname=="George Washington Colonials"
replace scode= 600 if sname=="Ga Southern"
replace scode= 600 if sname=="Georgia Southern Eagles"
replace scode= 601 if sname=="Gardner Webb"
replace scode= 601 if sname=="Gardner-Webb Runnin' Bulldogs"
replace scode= 602 if sname=="George Mason"
replace scode= 602 if sname=="George Mason Patriots"
replace scode= 603 if sname=="Georgetown"
replace scode= 603 if sname=="Georgetown Hoyas"
replace scode= 604 if sname=="Georgia"
replace scode= 604 if sname=="Georgia Bulldogs"
replace scode= 605 if sname=="Georgia St"
replace scode= 605 if sname=="Georgia State Panthers"
replace scode= 606 if sname=="Georgia Tech"
replace scode= 606 if sname=="Georgia Tech Yellow Jackets"
replace scode= 607 if sname=="Gonzaga"
replace scode= 607 if sname=="Gonzaga Bulldogs"
replace scode= 608 if sname=="Grambling"
replace scode= 608 if sname=="Grambling Tigers"
replace scode= 609 if sname=="Grand Canyon"
replace scode= 609 if sname=="Grand Canyon Antelopes"
replace scode= 610 if sname=="Hampton"
replace scode= 610 if sname=="Hampton Pirates"
replace scode= 611 if sname=="Hartford"
replace scode= 611 if sname=="Hartford Hawks"
replace scode= 612 if sname=="Harvard"
replace scode= 612 if sname=="Harvard Crimson"
replace scode= 613 if sname=="Hawaii"
replace scode= 613 if sname=="Hawaii Warriors"
replace scode= 614 if sname=="High Point"
replace scode= 614 if sname=="High Point Panthers"
replace scode= 615 if sname=="Hofstra"
replace scode= 615 if sname=="Hofstra Pride"
replace scode= 616 if sname=="Holy Cross"
replace scode= 616 if sname=="Holy Cross Crusaders"
replace scode= 617 if sname=="Houston"
replace scode= 617 if sname=="Houston Cougars"
replace scode= 618 if sname=="Houston Bap"
replace scode= 618 if sname=="Houston Baptist Huskies"
replace scode= 619 if sname=="Howard"
replace scode= 619 if sname=="Howard Bison"
replace scode= 620 if sname=="Idaho"
replace scode= 620 if sname=="Idaho Vandals"
replace scode= 621 if sname=="Idaho St"
replace scode= 621 if sname=="IL Chicago"
replace scode= 621 if sname=="Idaho State Bengals"
replace scode= 621 if sname=="Illinois State Redbirds"
replace scode= 622 if sname=="Illinois"
replace scode= 622 if sname=="Illinois-Chicago Flames"
replace scode= 623 if sname=="Illinois St"
replace scode= 623 if sname=="Illinois Fighting Illini"
replace scode= 625 if sname=="Indiana"
replace scode= 625 if sname=="Indiana Hoosiers"
replace scode= 626 if sname=="Indiana St"
replace scode= 626 if sname=="Indiana State Sycamores"
replace scode= 627 if sname=="Iona"
replace scode= 627 if sname=="Iona Gaels"
replace scode= 628 if sname=="Iowa"
replace scode= 628 if sname=="Iowa Hawkeyes"
replace scode= 629 if sname=="Iowa St"
replace scode= 629 if sname=="Iowa State Cyclones"
replace scode= 630 if sname=="IPFW"
replace scode= 630 if sname=="IPFW Mastodons"
replace scode= 631 if sname=="IUPUI"
replace scode= 631 if sname=="IUPUI Jaguars"
replace scode= 632 if sname=="Jackson St"
replace scode= 632 if sname=="Jackson State Tigers"
replace scode= 633 if sname=="Jacksonville"
replace scode= 633 if sname=="Jacksonville Dolphins"
replace scode= 634 if sname=="Jacksonville St"
replace scode= 634 if sname=="Jacksonville State Gamecocks"
replace scode= 635 if sname=="James Madison"
replace scode= 635 if sname=="James Madison Dukes"
replace scode= 636 if sname=="Kansas"
replace scode= 636 if sname=="Kansas Jayhawks"
replace scode= 637 if sname=="Kansas St"
replace scode= 637 if sname=="Kansas State Wildcats"
replace scode= 638 if sname=="Kennesaw"
replace scode= 638 if sname=="Kennesaw State Owls"
replace scode= 639 if sname=="Kent"
replace scode= 639 if sname=="Kent State Golden Flashes"
replace scode= 640 if sname=="Kentucky"
replace scode= 640 if sname=="Kentucky Wildcats"
replace scode= 641 if sname=="La Salle"
replace scode= 641 if sname=="La Salle Explorers"
replace scode= 642 if sname=="Lafayette"
replace scode= 642 if sname=="Lafayette Leopards"
replace scode= 643 if sname=="Lehigh"
replace scode= 643 if sname=="Lamar Cardinals"
replace scode= 644 if sname=="Liberty"
replace scode= 644 if sname=="Lehigh Mountain Hawks"
replace scode= 645 if sname=="Lipscomb"
replace scode= 645 if sname=="Liberty Flames"
replace scode= 646 if sname=="Long Beach St"
replace scode= 646 if sname=="Lipscomb Bisons"
replace scode= 647 if sname=="Long Island"
replace scode= 647 if sname=="Long Beach State 49ers"
replace scode= 648 if sname=="Longwood"
replace scode= 648 if sname=="Long Island University Blackbirds"
replace scode= 649 if sname=="Louisiana Tech"
replace scode= 649 if sname=="Longwood Lancers"
replace scode= 650 if sname=="Louisville"
replace scode= 650 if sname=="Louisiana Tech Bulldogs"
replace scode= 651 if sname=="Loy Marymount"
replace scode= 651 if sname=="Louisville Cardinals"
replace scode= 652 if sname=="Loyola MD"
replace scode= 652 if sname=="Loyola Marymount Lions"
replace scode= 653 if sname=="Loyola-Chicago"
replace scode= 653 if sname=="Loyola (MD) Greyhounds"
replace scode= 654 if sname=="LSU"
replace scode= 654 if sname=="Loyola (IL) Ramblers"
replace scode= 655 if sname=="MA Lowell"
replace scode= 655 if sname=="Louisiana State Fighting Tigers"
replace scode= 656 if sname=="Maine"
replace scode= 656 if sname=="Massachusetts-Lowell River Hawks"
replace scode= 657 if sname=="Manhattan"
replace scode= 657 if sname=="Maine Black Bears"
replace scode= 658 if sname=="Marist"
replace scode= 658 if sname=="Manhattan Jaspers"
replace scode= 659 if sname=="Marquette"
replace scode= 659 if sname=="Marist Red Foxes"
replace scode= 660 if sname=="Marshall"
replace scode= 660 if sname=="Marquette Golden Eagles"
replace scode= 661 if sname=="Maryland"
replace scode= 661 if sname=="Marshall Thundering Herd"
replace scode= 662 if sname=="Massachusetts"
replace scode= 662 if sname=="Maryland Terrapins"
replace scode= 663 if sname=="McNeese St"
replace scode= 663 if sname=="Massachusetts Minutemen"
replace scode= 664 if sname=="MD E Shore"
replace scode= 664 if sname=="McNeese State Cowboys"
replace scode= 665 if sname=="Memphis"
replace scode= 665 if sname=="Maryland-Eastern Shore Hawks"
replace scode= 666 if sname=="Mercer"
replace scode= 666 if sname=="Memphis Tigers"
replace scode= 667 if sname=="Miami FL"
replace scode= 667 if sname=="Mercer Bears"
replace scode= 668 if sname=="Miami OH"
replace scode= 668 if sname=="Miami (FL) Hurricanes"
replace scode= 669 if sname=="Michigan"
replace scode= 669 if sname=="Miami (OH) RedHawks"
replace scode= 670 if sname=="Michigan St"
replace scode= 670 if sname=="Michigan Wolverines"
replace scode= 671 if sname=="Middle Tenn St"
replace scode= 671 if sname=="Michigan State Spartans"
replace scode= 672 if sname=="Minnesota"
replace scode= 672 if sname=="Middle Tennessee Blue Raiders"
replace scode= 673 if sname=="Mississippi"
replace scode= 673 if sname=="Minnesota Golden Gophers"
replace scode= 674 if sname=="Mississippi St"
replace scode= 674 if sname=="Mississippi Rebels"
replace scode= 675 if sname=="Missouri"
replace scode= 675 if sname=="Mississippi State Bulldogs"
replace scode= 676 if sname=="Missouri KC"
replace scode= 676 if sname=="Missouri Tigers"
replace scode= 677 if sname=="Missouri St"
replace scode= 677 if sname=="Missouri-Kansas City Kangaroos"
replace scode= 678 if sname=="Monmouth NJ"
replace scode= 678 if sname=="Missouri State Bears"
replace scode= 679 if sname=="Montana"
replace scode= 679 if sname=="Monmouth Hawks"
replace scode= 680 if sname=="Montana St"
replace scode= 680 if sname=="Montana Grizzlies"
replace scode= 681 if sname=="Morehead St"
replace scode= 681 if sname=="Montana State Bobcats"
replace scode= 682 if sname=="Morgan St"
replace scode= 682 if sname=="Morehead State Eagles"
replace scode= 683 if sname=="Morris Brown"
replace scode= 683 if sname=="Morgan State Bears"
replace scode= 684 if sname=="MS Valley St"
replace scode= 684 if sname=="Morris Brown Wolverines"
replace scode= 685 if sname=="Mt St Mary's"
replace scode= 685 if sname=="Mississippi Valley State Delta Devils"
replace scode= 686 if sname=="Murray St"
replace scode= 686 if sname=="Mount St. Mary's Mountaineers"
replace scode= 687 if sname=="N Colorado"
replace scode= 687 if sname=="Murray State Breds"
replace scode= 688 if sname=="N Dakota St"
replace scode= 688 if sname=="Northern Colorado Bears"
replace scode= 689 if sname=="N Illinois"
replace scode= 689 if sname=="North Dakota State Bison"
replace scode= 690 if sname=="N Kentucky"
replace scode= 690 if sname=="Northern Illinois Huskies"
replace scode= 691 if sname=="Navy"
replace scode= 691 if sname=="Northern Kentucky Norse"
replace scode= 692 if sname=="NC A&T"
replace scode= 692 if sname=="Navy Midshipmen"
replace scode= 693 if sname=="NC Central"
replace scode= 693 if sname=="NC A&T"
replace scode= 694 if sname=="NC State"
replace scode= 694 if sname=="North Carolina Central Eagles"
replace scode= 695 if sname=="NE Illinois"
replace scode= 695 if sname=="North Carolina State Wolfpack"
replace scode= 696 if sname=="NE Omaha"
replace scode= 696 if sname=="Northeastern Illinois Golden Eagles"
replace scode= 697 if sname=="Nebraska"
replace scode= 697 if sname=="Nebraska-Omaha Mavericks"
replace scode= 698 if sname=="Nevada"
replace scode= 698 if sname=="Nebraska Cornhuskers"
replace scode= 699 if sname=="New Hampshire"
replace scode= 699 if sname=="Nevada Wolf Pack"
replace scode= 700 if sname=="New Mexico"
replace scode= 700 if sname=="New Hampshire Wildcats"
replace scode= 701 if sname=="New Mexico St"
replace scode= 701 if sname=="New Mexico Lobos"
replace scode= 702 if sname=="New Orleans"
replace scode= 702 if sname=="New Mexico State Aggies"
replace scode= 703 if sname=="Niagara"
replace scode= 703 if sname=="New Orleans Privateers"
replace scode= 704 if sname=="Nicholls St"
replace scode= 704 if sname=="Niagara Purple Eagles"
replace scode= 705 if sname=="NJIT"
replace scode= 705 if sname=="Nicholls State Colonels"
replace scode= 706 if sname=="Norfolk St"
replace scode= 706 if sname=="NJIT Highlanders"
replace scode= 707 if sname=="North Carolina"
replace scode= 707 if sname=="Norfolk State Spartans"
replace scode= 708 if sname=="North Dakota"
replace scode= 708 if sname=="North Florida"
replace scode= 708 if sname=="North Carolina A&T Aggies"
replace scode= 708 if sname=="North Carolina Tar Heels"
replace scode= 709 if sname=="North Texas"
replace scode= 709 if sname=="North Dakota UND"
replace scode= 710 if sname=="Northeastern"
replace scode= 710 if sname=="North Florida Ospreys"
replace scode= 711 if sname=="Northern Arizona"
replace scode= 711 if sname=="North Texas Mean Green"
replace scode= 712 if sname=="Northern Iowa"
replace scode= 712 if sname=="Northeastern Huskies"
replace scode= 713 if sname=="Northwestern"
replace scode= 713 if sname=="Northern Arizona Lumberjacks"
replace scode= 714 if sname=="Northwestern LA"
replace scode= 714 if sname=="Northern Iowa Panthers"
replace scode= 715 if sname=="Notre Dame"
replace scode= 715 if sname=="Northwestern Wildcats"
replace scode= 716 if sname=="Oakland"
replace scode= 716 if sname=="Northwestern State Demons"
replace scode= 717 if sname=="Ohio"
replace scode= 717 if sname=="Notre Dame Fighting Irish"
replace scode= 718 if sname=="Ohio St"
replace scode= 718 if sname=="Oakland Golden Grizzlies"
replace scode= 719 if sname=="Oklahoma"
replace scode= 719 if sname=="Ohio Bobcats"
replace scode= 720 if sname=="Oklahoma St"
replace scode= 720 if sname=="Ohio State Buckeyes"
replace scode= 721 if sname=="Old Dominion"
replace scode= 721 if sname=="Oklahoma Sooners"
replace scode= 722 if sname=="Oral Roberts"
replace scode= 722 if sname=="Oklahoma State Cowboys"
replace scode= 723 if sname=="Oregon"
replace scode= 723 if sname=="Old Dominion Monarchs"
replace scode= 724 if sname=="Oregon St"
replace scode= 724 if sname=="Oral Roberts Golden Eagles"
replace scode= 725 if sname=="Pacific"
replace scode= 725 if sname=="Oregon Ducks"
replace scode= 726 if sname=="Penn"
replace scode= 726 if sname=="Oregon State Beavers"
replace scode= 727 if sname=="Penn St"
replace scode= 727 if sname=="Pacific Tigers"
replace scode= 728 if sname=="Pepperdine"
replace scode= 728 if sname=="Pennsylvania Quakers"
replace scode= 729 if sname=="Pittsburgh"
replace scode= 729 if sname=="Penn State Nittany Lions"
replace scode= 730 if sname=="Portland"
replace scode= 730 if sname=="Pepperdine Waves"
replace scode= 731 if sname=="Portland St"
replace scode= 731 if sname=="Pittsburgh Panthers"
replace scode= 732 if sname=="Prairie View"
replace scode= 732 if sname=="Portland Pilots"
replace scode= 733 if sname=="Presbyterian"
replace scode= 733 if sname=="Portland State Vikings"
replace scode= 734 if sname=="Princeton"
replace scode= 734 if sname=="Prairie View Panthers"
replace scode= 735 if sname=="Providence"
replace scode= 735 if sname=="Presbyterian Blue Hose"
replace scode= 736 if sname=="Purdue"
replace scode= 736 if sname=="Princeton Tigers"
replace scode= 737 if sname=="Quinnipiac"
replace scode= 737 if sname=="Providence Friars"
replace scode= 738 if sname=="Radford"
replace scode= 738 if sname=="Purdue Boilermakers"
replace scode= 739 if sname=="Rhode Island"
replace scode= 739 if sname=="Quinnipiac Bobcats"
replace scode= 740 if sname=="Rice"
replace scode= 740 if sname=="Radford Highlanders"
replace scode= 741 if sname=="Richmond"
replace scode= 741 if sname=="Rhode Island Rams"
replace scode= 742 if sname=="Rider"
replace scode= 742 if sname=="Rice Owls"
replace scode= 743 if sname=="Robert Morris"
replace scode= 743 if sname=="Richmond Spiders"
replace scode= 744 if sname=="Rutgers"
replace scode= 744 if sname=="Rider Broncs"
replace scode= 745 if sname=="S Carolina St"
replace scode= 745 if sname=="Robert Morris Colonials"
replace scode= 746 if sname=="S Dakota St"
replace scode= 746 if sname=="Rutgers Scarlet Knights"
replace scode= 747 if sname=="S Illinois"
replace scode= 747 if sname=="South Carolina State Bulldogs"
replace scode= 748 if sname=="Sacred Heart"
replace scode= 748 if sname=="South Dakota State Jackrabbits"
replace scode= 749 if sname=="Sam Houston St"
replace scode= 749 if sname=="Southern Illinois Salukis"
replace scode= 750 if sname=="Samford"
replace scode= 750 if sname=="Sacred Heart Pioneers"
replace scode= 751 if sname=="San Diego"
replace scode= 751 if sname=="Sam Houston State Bearkats"
replace scode= 752 if sname=="San Diego St"
replace scode= 752 if sname=="Samford Bulldogs"
replace scode= 753 if sname=="San Francisco"
replace scode= 753 if sname=="San Diego Toreros"
replace scode= 754 if sname=="San Jose St"
replace scode= 754 if sname=="San Diego State Aztecs"
replace scode= 755 if sname=="Santa Barbara"
replace scode= 755 if sname=="San Francisco Dons"
replace scode= 756 if sname=="Santa Clara"
replace scode= 756 if sname=="San Jose State Spartans"
replace scode= 757 if sname=="Savannah St"
replace scode= 757 if sname=="UC Santa Barbara"
replace scode= 758 if sname=="SC Upstate"
replace scode= 758 if sname=="Santa Clara Broncos"
replace scode= 759 if sname=="SE Louisiana"
replace scode= 759 if sname=="Savannah State Tigers"
replace scode= 760 if sname=="SE Missouri St"
replace scode= 760 if sname=="South Carolina Upstate Spartans"
replace scode= 761 if sname=="Seattle"
replace scode= 761 if sname=="Southeastern Louisiana Lions"
replace scode= 762 if sname=="Seton Hall"
replace scode= 762 if sname=="Southeast Missouri State Redhawks"
replace scode= 763 if sname=="SF Austin"
replace scode= 763 if sname=="Seattle Redhawks"
replace scode= 764 if sname=="Siena"
replace scode= 764 if sname=="Seton Hall Pirates"
replace scode= 765 if sname=="SMU"
replace scode= 765 if sname=="Stephen F. Austin Lumberjacks"
replace scode= 766 if sname=="South Alabama"
replace scode= 766 if sname=="Siena Saints"
replace scode= 767 if sname=="South Carolina"
replace scode= 767 if sname=="Southern Methodist Mustangs"
replace scode= 768 if sname=="South Dakota"
replace scode= 768 if sname=="South Alabama Jaguars"
replace scode= 769 if sname=="South Florida"
replace scode= 769 if sname=="South Carolina Gamecocks"
replace scode= 770 if sname=="Southern Miss"
replace scode= 770 if sname=="South Dakota Coyotes"
replace scode= 771 if sname=="Southern Univ"
replace scode= 771 if sname=="South Florida Bulls"
replace scode= 772 if sname=="Southern Utah"
replace scode= 772 if sname=="Southern Mississippi Golden Eagles"
replace scode= 773 if sname=="St Bonaventure"
replace scode= 773 if sname=="Southern Jaguars"
replace scode= 774 if sname=="St Francis NY"
replace scode= 774 if sname=="Southern Utah Thunderbirds"
replace scode= 775 if sname=="St Francis PA"
replace scode= 775 if sname=="St. Bonaventure Bonnies"
replace scode= 776 if sname=="St John's"
replace scode= 776 if sname=="St. Francis (NY) Terriers"
replace scode= 777 if sname=="St Joseph's PA"
replace scode= 777 if sname=="Saint Francis (PA) Red Flash"
replace scode= 778 if sname=="St Louis"
replace scode= 778 if sname=="St. John's (NY) Red Storm"
replace scode= 779 if sname=="St Mary's CA"
replace scode= 779 if sname=="Saint Joseph's Hawks"
replace scode= 780 if sname=="St Peter's"
replace scode= 780 if sname=="Saint Louis Billikens"
replace scode= 781 if sname=="Stanford"
replace scode= 781 if sname=="Saint Mary's (CA) Gaels"
replace scode= 782 if sname=="Stetson"
replace scode= 782 if sname=="Saint Peter's Peacocks"
replace scode= 783 if sname=="Stony Brook"
replace scode= 783 if sname=="Stanford Cardinal"
replace scode= 784 if sname=="Syracuse"
replace scode= 784 if sname=="Stetson Hatters"
replace scode= 785 if sname=="TAM C. Christi"
replace scode= 785 if sname=="Stony Brook Seawolves"
replace scode= 786 if sname=="TCU"
replace scode= 786 if sname=="Syracuse Orange"
replace scode= 788 if sname=="Temple"
replace scode= 788 if sname=="Texas Christian Horned Frogs"
replace scode= 789 if sname=="Tennessee"
replace scode= 789 if sname=="Temple Owls"
replace scode= 790 if sname=="Tennessee St"
replace scode= 790 if sname=="Tennessee Volunteers"
replace scode= 791 if sname=="Tennessee Tech"
replace scode= 791 if sname=="Tennessee State Tigers"
replace scode= 792 if sname=="Texas"
replace scode= 792 if sname=="Tennessee Tech Golden Eagles"
replace scode= 793 if sname=="Texas A&M"
replace scode= 793 if sname=="Texas Longhorns"
replace scode= 794 if sname=="Texas St"
replace scode= 794 if sname=="Texas A&M Aggies"
replace scode= 795 if sname=="Texas Tech"
replace scode= 795 if sname=="Texas State Bobcats"
replace scode= 796 if sname=="TN Martin"
replace scode= 796 if sname=="Texas Tech Red Raiders"
replace scode= 797 if sname=="Toledo"
replace scode= 797 if sname=="Tennessee-Martin Skyhawks"
replace scode= 798 if sname=="Towson"
replace scode= 798 if sname=="Toledo Rockets"
replace scode= 799 if sname=="Troy"
replace scode= 799 if sname=="Towson Tigers"
replace scode= 800 if sname=="Tulane"
replace scode= 800 if sname=="Troy Trojans"
replace scode= 801 if sname=="Tulsa"
replace scode= 801 if sname=="Tulane Green Wave"
replace scode= 802 if sname=="TX Pan American"
replace scode= 802 if sname=="Tulsa Golden Hurricane"
replace scode= 803 if sname=="TX Southern"
replace scode= 803 if sname=="Texas-Pan American Broncs"
replace scode= 804 if sname=="UAB"
replace scode= 804 if sname=="Texas Southern Tigers"
replace scode= 806 if sname=="UC Davis"
replace scode= 806 if sname=="California-Davis Aggies"
replace scode= 807 if sname=="UC Irvine"
replace scode= 807 if sname=="California-Irvine Anteaters"
replace scode= 808 if sname=="UC Riverside"
replace scode= 808 if sname=="California-Riverside Highlanders"
replace scode= 809 if sname=="UCF"
replace scode= 809 if sname=="Central Florida Knights"
replace scode= 810 if sname=="UCLA"
replace scode= 810 if sname=="UCLA Bruins"
replace scode= 811 if sname=="Lamar"
replace scode= 811 if sname=="ULL"
replace scode= 811 if sname=="Louisiana-Lafayette Ragin' Cajuns"
replace scode= 811 if sname=="ULL (Lousiania Lafayette)"
replace scode= 812 if sname=="ULM"
replace scode= 812 if sname=="Louisiana-Monroe Warhawks"
replace scode= 813 if sname=="UMBC"
replace scode= 813 if sname=="Maryland-Baltimore County Retrievers"
replace scode= 814 if sname=="UNC Asheville"
replace scode= 814 if sname=="North Carolina-Asheville Bulldogs"
replace scode= 815 if sname=="UNC Greensboro"
replace scode= 815 if sname=="North Carolina-Greensboro Spartans"
replace scode= 816 if sname=="UNC Wilmington"
replace scode= 816 if sname=="North Carolina-Wilmington Seahawks"
replace scode= 817 if sname=="UNLV"
replace scode= 817 if sname=="Nevada-Las Vegas Rebels"
replace scode= 818 if sname=="USC"
replace scode= 818 if sname=="Southern California Trojans"
replace scode= 819 if sname=="UT Arlington"
replace scode= 819 if sname=="Texas-Arlington Mavericks"
replace scode= 820 if sname=="UT San Antonio"
replace scode= 820 if sname=="Texas-San Antonio Roadrunners"
replace scode= 821 if sname=="Utah"
replace scode= 821 if sname=="Utah Utes"
replace scode= 822 if sname=="Utah St"
replace scode= 822 if sname=="Utah State Aggies"
replace scode= 823 if sname=="Utah Valley"
replace scode= 823 if sname=="Utah Valley Wolverines"
replace scode= 824 if sname=="UTEP"
replace scode= 824 if sname=="Texas-El Paso Miners"
replace scode= 825 if sname=="VA Commonwealth"
replace scode= 825 if sname=="Virginia Commonwealth Rams"
replace scode= 826 if sname=="Valparaiso"
replace scode= 826 if sname=="Valparaiso Crusaders"
replace scode= 827 if sname=="Vanderbilt"
replace scode= 827 if sname=="Vanderbilt Commodores"
replace scode= 828 if sname=="Vermont"
replace scode= 828 if sname=="Vermont Catamounts"
replace scode= 829 if sname=="Villanova"
replace scode= 829 if sname=="Villanova Wildcats"
replace scode= 830 if sname=="Virginia"
replace scode= 830 if sname=="Virginia Cavaliers"
replace scode= 831 if sname=="Virginia Tech"
replace scode= 831 if sname=="Virginia Tech Hokies"
replace scode= 832 if sname=="VMI"
replace scode= 832 if sname=="Virginia Military Institute Keydets"
replace scode= 833 if sname=="W Carolina"
replace scode= 833 if sname=="Western Carolina Catamounts"
replace scode= 834 if sname=="W Illinois"
replace scode= 834 if sname=="Western Illinois Leathernecks"
replace scode= 835 if sname=="W Kentucky"
replace scode= 835 if sname=="Western Kentucky Hilltoppers"
replace scode= 836 if sname=="W Michigan"
replace scode= 836 if sname=="Western Michigan Broncos"
replace scode= 837 if sname=="W Salem St"
replace scode= 837 if sname=="W Salem St"
replace scode= 838 if sname=="Wagner"
replace scode= 838 if sname=="Wagner Seahawks"
replace scode= 839 if sname=="Wake Forest"
replace scode= 839 if sname=="Wake Forest Demon Deacons"
replace scode= 840 if sname=="Washington"
replace scode= 840 if sname=="Washington Huskies"
replace scode= 841 if sname=="Washington St"
replace scode= 841 if sname=="Washington State Cougars"
replace scode= 842 if sname=="Weber St"
replace scode= 842 if sname=="Weber State Wildcats"
replace scode= 843 if sname=="West Virginia"
replace scode= 843 if sname=="West Virginia Mountaineers"
replace scode= 844 if sname=="WI Green Bay"
replace scode= 844 if sname=="Green Bay Phoenix"
replace scode= 845 if sname=="WI Milwaukee"
replace scode= 845 if sname=="Milwaukee Panthers"
replace scode= 846 if sname=="Wichita St"
replace scode= 846 if sname=="Wichita State Shockers"
replace scode= 847 if sname=="William & Mary"
replace scode= 847 if sname=="William & Mary Tribe"
replace scode= 848 if sname=="Winthrop"
replace scode= 848 if sname=="Winthrop Eagles"
replace scode= 849 if sname=="Wisconsin"
replace scode= 849 if sname=="Wisconsin Badgers"
replace scode= 850 if sname=="Wofford"
replace scode= 850 if sname=="Wofford Terriers"
replace scode= 851 if sname=="Wright St"
replace scode= 851 if sname=="Wright State Raiders"
replace scode= 852 if sname=="Wyoming"
replace scode= 852 if sname=="Wyoming Cowboys"
replace scode= 853 if sname=="Xavier"
replace scode= 853 if sname=="Xavier Musketeers"
replace scode= 854 if sname=="Yale"
replace scode= 854 if sname=="Yale Elis"
replace scode= 855 if sname=="Youngstown St"
replace scode= 855 if sname=="Youngstown State Penguins"
replace scode= 856 if sname=="Incarnate Word"
replace scode= 856 if sname=="Incarnate Word Cardinals"
